INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = BackTrackSpotify

BackTrackSpotify_FILES = Tweak.x
BackTrackSpotify_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
