INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = IconLabelRemover

IconLabelRemover_FILES = Tweak.x
IconLabelRemover_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
